### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by Gui1105** [Sp4c3-blockchain/AIpower-Proving-Program#1]
![image](https://user-images.githubusercontent.com/29769388/144537352-c8c9fc0c-ebda-4a7f-9e66-4d0181e3c1c2.png)

`
AI Running Mode: 
Fail to start AI Enviroment, program will exit.
`

What was the mistake  ?

**Comment by Sp4c3-blockchain** [comment]
Something was missed in ur AI Environment, and a new package will be updated to show what u missed in a few hours.

**Comment by Gui1105** [comment]
> Something was missed in ur AI Environment, and a new package will be updated to show what u missed in a few hours.

Thank you, look forward to

**Comment by Gui1105** [comment]
Hello, have updated it?

**Comment by Sp4c3-blockchain** [comment]
Try this for your Power Providing: https://sp4.s3.ap-east-1.amazonaws.com/install/sp4ubuntu.tar-1.0.1.gz
